### ISSUE TITLE
install instructions insufficient - pulls in cryodrgn/3.x but needs cryodrgn/2.3.0

### ISSUE THREAD

**Issue by schloegl** [ma-gilles/recovar#3]
recovar can not be used when following the install instructions of using 
   pip install cryodrgn

this wil pull in cryodrgn/3.4.0, but only cryodrgn/2.3.0 will work with recovar. 

Because it took quite some time to identify the problem I suggest to either fix the installation instructions, or to fix the code such that it will work with recent cryodrgn as well.

**Comment by ma-gilles** [comment]
Thank you very much for pointing it out. I made a note of it and will fix versioning issues when I have time. The fix right now is to install cryodrgn in a different conda environment than recovar. Then use cryodrgn to preprocess the data, and only then activate the recovar conda environement.

**Comment by schloegl** [comment]
I see now that you have in recovar_install_requirements.txt the line 
    cryodrgn==2.3.0

I've disabled all version requirements, because these were too restricting in my environment. So, I discarded this version requirement. I guess the error is on my side. If you are interested, I can send you the "pip freeze" that is working for me.
